filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    include_lines: ['MY_LOG']
    fields:
      service: my_python_app

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

#output.console:
#  enabled: true

logging.json: true
logging.metrics.enabled: false
