FROM centos:centos7

ENV MOLECULE_NO_LOG false
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN yum update -y
RUN yum install sudo glibc-common epel-release yum-utils vim -y
RUN yum install tar gcc make python3-pip zlib-devel openssl-devel libffi-devel docker -y

ADD https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tgz Python-3.7.10.tgz
RUN tar xf Python-3.7.10.tgz && cd Python-3.7.10/ && ./configure && make && make altinstall

ADD https://www.python.org/ftp/python/3.9.2/Python-3.9.2.tgz Python-3.9.2.tgz
RUN tar xf Python-3.9.2.tgz && cd Python-3.9.2/ && ./configure && make && make altinstall

RUN python3.9 -m pip install --upgrade pip
RUN python3.9 -m pip install ansible && pip3 install "ansible-lint<6.0.0"
RUN pip3 install molecule==3.4.0 molecule_docker && pip3 install tox selinux

RUN rm -rf Python-*

RUN yum install python3-libselinux python-flake8 -y
