galaxy_info:
  role_name: clickhouse_role
  namespace: olezhuravlev
  author: Oleg Zhuravlev (and thanks to Alexey Setevoi)
  description: Role for installation and managing ClickHouse (taken from github.com/AlexeySetevoi/ansible-clickhouse but default config.xml and users.xml applied).

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - clickhouse
    - database
    - sql

dependencies: []
