{
 "title": "Netology Dashboard Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Exporter CPU Utilization Panel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (irate(node_cpu_seconds_total{instance=\"node-exporter-node1:9100\", mode!=\"idle\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter-node1:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=\"node-exporter-node1:9100\"}",
     "legendFormat": "__auto"
    },
    { "expr": "node_load15", "legendFormat": "Auto" }
   ]
  },
  {
   "title": "Available RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node-exporter-node1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node-exporter-node1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}