global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'node-exporter-node1'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter-node1:9100']
