server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: "http://kibana:5601"
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.hosts: [ "http://es-hot:9200" ]
elasticsearch.username: elastic
elasticsearch.password: elastic
